asgweb_service_state: 'present'

vpc_region: 'us-west-2'
vpc_name: 'gitlab'
vpc_id: 'vpc-6461cf02'

ec2_cluster_name: 'gitlab'
ec2_ami: 'ami-0bf61373'
ec2_instance_type: 't2.medium'
ec2_assign_public_ip: false
ec2_instance_profile_name: 'gitlab'

manage_elb: true
manage_cert: true

asg_health_check_period: 300
asg_health_check_timeout: 600
asg_health_check_type: 'ELB'

elb_domain: 'gitlab.wlnpcc.ca'
elb_listeners:
  - protocol: http
    load_balancer_port: 80
    instance_port: "{{ elb_host_port }}"
    proxy_protocol: True
  - protocol: https
    load_balancer_port: 443
    instance_protocol: http
    instance_port: "{{ elb_host_port }}"
    ssl_certificate_id: "{{ elb_cert_arn }}"
  - protocol: tcp
    load_balancer_port: 22
    instance_protocol: tcp
    instance_port: 22
elb_health_check:
  ping_protocol: http
  ping_port: '80'
  ping_path: "/users/sign_in"    # only required for http/https
  response_timeout: 5
  interval: 25
  unhealthy_threshold: 10
  healthy_threshold: 2

# dots in this name will cause ansible to throw
# ssl verification errors. https://github.com/ansible/ansible-modules-core/issues/1183
s3_bucket_name: "wlnpcc_gitlab_backups"

ssl_certs_common_name: "gitlab.wlnpcc.ca"
ssl_certs_path: "/tmp"
ssl_certs_path_owner: "root"
ssl_certs_path_group: "root"

instance_sg_rules:
  - proto: tcp
    from_port: 80
    to_port:  80
    cidr_ip: '0.0.0.0/0'
  - proto: tcp
    from_port: 443
    to_port:  443
    cidr_ip: '0.0.0.0/0'
  - proto: tcp
    from_port: 22
    to_port: 22
    cidr_ip: '0.0.0.0/0'
  - proto: tcp
    from_port: 2222
    to_port: 2222
    cidr_ip: '0.0.0.0/0'
  - proto: tcp
    from_port: 2049
    to_port: 2049
    cidr_ip: '10.0.0.0/16'
