---
- name: Build out a GitLab "cluster" in AWS
  hosts: all
  connection: local
  tasks:
    - name: manage instance profile to allow CI runner to launch instances
      local_action:
        module: iam_role
        name: "{{ ec2_instance_profile_name }}"
        state: "{{ asgweb_service_state }}"
        assume_role_policy_document: |
          {
            "Version" : "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Service": [ "ec2.amazonaws.com" ]
                },
                "Action": [ "sts:AssumeRole" ]
              }
            ]
          }
        managed_policy:
          - 'arn:aws:iam::aws:policy/AmazonElasticFileSystemFullAccess'
          - 'arn:aws:iam::aws:policy/AmazonEC2FullAccess'
          - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'

    - name: manage s3 bucket for backups
      local_action:
        module: s3_bucket
        name: "{{ s3_bucket_name }}"
        state: "{{ asgweb_service_state }}"

    - name: build autoscale group
      include_role: name=inhumantsar.ec2-asgweb
