---
- name: Build out a GitLab "cluster" in AWS
  hosts: all
  connection: local

  tasks:
    - name: create vpc
      include_role:
        name: inhumantsar.ec2-vpc

    - name: create instance profile to allow CI runner to launch instances
      local_action:
        module: iam_role
        name: "{{ ec2_instance_profile_name }}"
        state: present
        managed_policy:
          - 'arn:aws:iam::aws:policy/AmazonEC2FullAccess'

    - name: run the asgweb
      include_role: name=inhumantsar.ec2-asgweb
