vpc_cidr: '10.0.0.0/16'
vpc_region: 'us-west-2'
vpc_name: 'gitlab'
vpc_public_subnet_cidrs:
  - '10.0.1.0/24'
  - '10.0.2.0/24'
vpc_public_subnet_azs:
  '10.0.1.0/24': 'a'
  '10.0.2.0/24': 'b'

ec2_cluster_name: 'gitlab'
ec2_ami: 'ami-a40912dd'
ec2_instance_type: 't2.medium'
ec2_assign_public_ip: 'yes'

manage_elb: false
manage_cert: false
asg_health_check_type: 'EC2'


# vars file for dummy-role
ssl_certs_common_name: "{{ elb_cert_domain }}"
ssl_certs_path: "/tmp"
ssl_certs_path_owner: "root"
ssl_certs_path_group: "root"


instance_sg_rules:
  - proto: tcp
    from_port: 80
    to_port:  80
    cidr_ip: '0.0.0.0/0'
  - proto: tcp
    from_port: 443
    to_port:  443
    cidr_ip: '0.0.0.0/0'
  - proto: tcp
    from_port: 22
    to_port: 22
    cidr_ip: '0.0.0.0/0'
  - proto: tcp
    from_port: 2222
    to_port: 2222
    cidr_ip: '0.0.0.0/0'
